### ISSUE TITLE
Backend - User information set cookie for refresh page

### ISSUE THREAD

**Issue by berkantesk** [kocun/heida#10]
Sayfa yenilendiğinde login sayfasına geri dönüyor. Cookie den kullanıcı bilgilerini okuyup sürekli dashboard da kalmasının sağlanması.

User info set cookie for refresh page.

**Comment by adilatilgan** [comment]
Zafer before you go please discuss with me with the solution.

**Comment by berkantesk** [comment]
Done, it's work.
