### ISSUE TITLE
Frontend - Reports page columns to add and filter function

### ISSUE THREAD

**Issue by melissaabache** [kocun/heida#106]
@berkantesk @ogzhnozlci @adilatilgan  just checked new deployment thanks! and we still need to fix the following on Reports page:

First table: 
- add a title that says "Filter by unit" above the first table
- add "Name of Unit" column that shows name of unit that has completed an indicator
- delete "Indicator" as it is not working on a conditional basis
- when clicking "Filter" the second table should only show indicators completed by that Unit-Sub-Unit-Name of Unit (conditional)

Add a new table with title "Filter by internationalisation goals and dimensions"
Table columns will be (in this order):
- Goal (showing the 5 goals as drop down list - single choice)
- Group (showing 9 groups as drop-down list - single choice)
- Sub-Group (showing only sub-groups linked to the chosen Group - multiple choice)
Button FILTER
Button CLEAR
When clicking filter it would show only those indicators that have been completed belonging to the selected Goal - Group - Sub-Group for all Units available

Second table:
Columns that need to appear (in this order)
- Indicator Code 
- Indicator Name
- Unit
- Sub-Unit
- **Name of Unit (very important!)**
- Status
- **Delete "Data type" column (not necessary)**
- Actions (Edit, Visualize, Print, Delete)

![image](https://cloud.githubusercontent.com/assets/16255219/19429286/8799d21a-9457-11e6-903b-0b8033dc73ed.png)

**Comment by ogzhnozlci** [comment]
Hi Melissa,
Do you make a list about all **"new request"** for us? Working like this ( **telling new requests one by one** ) is very hard. 

By the way, "Name of Unit" column added to table. You may clear your browser cache and check this page again.

**Comment by melissaabache** [comment]
Putting all Reports page requests into a new issue called "New requests" as requested by @ogzhnozlci
