### ISSUE TITLE
Frontend - Add Data page - adding values for Yes/No type indicators

### ISSUE THREAD

**Issue by melissaabache** [kocun/heida#109]
@adilatilgan @ogzhnozlci @berkantesk On Add Data page when I select a yes/no type indicator it is not letting me add the answer (yes/no) (see screenshot) and so the report is coming out blank too. Please fix this

![image](https://cloud.githubusercontent.com/assets/16255219/19430007/2d0cb246-945b-11e6-91de-e3062ed71c85.png)

**Comment by ogzhnozlci** [comment]
Done
