### ISSUE TITLE
Frontend - Reports Page - ALL REQUESTS

### ISSUE THREAD

**Issue by melissaabache** [kocun/heida#110]
@adilatilgan @ogzhnozlci @berkantesk  just checked new deployment thanks! and we still need to fix the following on Reports page:

First table:
• add a title that says "Filter by unit" above the first table
• add "Name of Unit" column that shows name of unit that has completed an indicator
• delete "Indicator" as it is not working on a conditional basis
• when clicking "Filter" the second table should only show indicators completed by that Unit-Sub-Unit-Name of Unit (conditional)

Add a new table with title "Filter by internationalisation goals and dimensions"

Table columns will be (in this order):
• Goal (showing the 5 goals as drop down list - single choice)
• Group (showing 9 groups as drop-down list - single choice)
• Sub-Group (showing only sub-groups linked to the chosen Group - multiple choice) Button FILTER Button CLEAR When clicking filter it would show only those indicators that have been completed belonging to the selected Goal - Group - Sub-Group for all Units available

Second table:
Columns that need to appear (in this order)
• Indicator Code
• Indicator Name
• Unit
• Sub-Unit (not showing name right now)
• Name of Unit (very important!)
• Status
• Delete "Data type" column (not necessary)
• Actions (Edit, Visualize, Print, Delete)

On Reports page when clicking on Visualize the following data should show:

1) Graph (please make smaller if possible)

2) Below graph: in this order
• Unit
• Sub-Unit
• Name of Unit (very important!)
• Group -Sub-Group
• Indicator Code
• Indicator Name
• Value type
• Public: Yes / No
• Values for selected year as table
• Criteria 1 and answer
• Criteria 2 and answer
• Criteria 3 and answer
• Criteria 4 and answer
• Criteria 5 and answer
• Criteria 6 and answer
• Criteria 7 and answer
• Criteria 8 and answer
• Date when report was created (if possible?)

On Reports page when clicking on Print the following data should show:

1) Graph (please make smaller if possible)

2) Below graph: in this order
• Unit
• Sub-Unit
• Name of Unit (very important!)
• Group -Sub-Group
• Indicator Code
• Indicator Name
• Value type
• Public: Yes / No
• Values for selected year as table
• Criteria 1 and answer
• Criteria 2 and answer
• Criteria 3 and answer
• Criteria 4 and answer
• Criteria 5 and answer
• Criteria 6 and answer
• Criteria 7 and answer
• Criteria 8 and answer
• Date when report was created (if possible?)

**Comment by melissaabache** [comment]
@berkantesk here is the powerpoint image showing how Reports page should look like regarding filters. I'm also sending it as an email. 
![reports page final design](https://cloud.githubusercontent.com/assets/16255219/19517626/041f54a4-960b-11e6-8abd-41f365713077.jpg)

@berkantesk on Reports page - Visualize - for Yes/No indicators the values are not showing (see image below) - please fix

![reports page visualize yes no type indicators not showing](https://cloud.githubusercontent.com/assets/16255219/19517644/24dbe996-960b-11e6-92d7-54027aefb3a2.jpg)

@berkantesk on "Add Data" page for Criteria 3 and Criteria 7 the "Other" option needs to be the last one on the list (see image below) - please fix

![other position for criteria 3 and criteria 7](https://cloud.githubusercontent.com/assets/16255219/19517754/b31c99da-960b-11e6-9f47-c2b488cbdab4.jpg)

@berkantesk on "Add Data" page for Criteria 3,4,5, 7 and 8 if "Other" is selected there should be an open text box to write down the name of the "Other" answer (I remember I said this to @ogzhnozlci in one of our early meetings) - please fix

@berkantesk on Left Hand side menu the name should be "+Add Data" not "+Create Data"

Thanks

**Comment by ogzhnozlci** [comment]
1- Report Page filter revisions done. (can't use name of unit. Because of there is no a list on backend for this info. )
2-  Report Detail Page "yes/no" value fixed.
3- Can't change order of "other" item in list on FrontEnd. "other" item is on list which is coming from backend.
4- Can't open a text box when user choose "other" in criterias. Because of there is no support on backend for this data. Also if it will be done, all pages which has criterias edit or view inside, must be overhauling.
( @melissaabache i remember that we talked this about department name, not about criterias. Also i didn't find any info in our mails or issues about this subject )
5- on side menu, "Create Data" is changed to "Add Data"

@adilatilgan I sent a PR for these developments.

fyi @melissaabache @adilatilgan @berkantesk

**Comment by melissaabache** [comment]
@adilatilgan Hi Adil checking remaining issues please see below:

On Reports page when clicking on Print the following data should show: (not showing right now)

Graph (please make smaller if possible)

Below graph: in this order
• Unit
• Sub-Unit
• Name of Unit (very important!)
• Group -Sub-Group
• Indicator Code
• Indicator Name
• Value type
• Public: Yes / No
• Values for selected year as table
• Criteria 1 and answer
• Criteria 2 and answer
• Criteria 3 and answer
• Criteria 4 and answer
• Criteria 5 and answer
• Criteria 6 and answer
• Criteria 7 and answer
• Criteria 8 and answer
• Date when report was created (if possible?)

**Comment by berkantesk** [comment]
Hi Melissa,
you see the page on browser cache. Please delete the cache and try again?

Thanks.

**Comment by berkantesk** [comment]
Fixed last month.
