### ISSUE TITLE
Backend - Status on Reports Page - Incomplete/Complete

### ISSUE THREAD

**Issue by melissaabache** [kocun/heida#116]
@adilatilgan @zafertaskent please fix on the Reports page the "Status" of the indicators. Right now they all show as "Incomplete". When  user "saves" data for an indicator it should show "Complete". Not sure if this is frontend or backend
Thanks
Melissa

**Comment by melissaabache** [comment]
@adilatilgan @zafertaskent to provide further guidance:
When user starts to add data for an indicator (unit, sub-unit, value, criterias, etc) but doesn't have all the information please allow user to "save" the information. In this case on the Reports page this indicator would show as "Incomplete"

When users adds all data for an indicator and clicks on "save" then on the Reports page this indicator would show as "Complete"

Thanks

Melissa

**Comment by berkantesk** [comment]
User must choose the department or year in case. User can not empty all fields and i think this situation is correct. @adilatilgan @melissaabache @zafertaskent @ogzhnozlci

**Comment by melissaabache** [comment]
@berkantesk @adilatilgan OK then on Add Data if the user has not added "Department" or "Year" please create a "pop-up" message that says "You must choose a Department and/or Year to save your selection"
Thanks

**Comment by berkantesk** [comment]
@melissaabache @adilatilgan 
hi Melissa, 
your last request fixed.
