### ISSUE TITLE
Frontend - Reports page for View-Only users

### ISSUE THREAD

**Issue by melissaabache** [kocun/heida#118]
@adilatilgan @berkantesk hello sorry about this but just noticed a problem with the Reports page for "View-Only" users. Right now it shows as actions "Edit" "Visualize" "Print" and "Delete".

Please delete from "View-Only" user permissions on Reports page "Edit" and "Delete". They should only see "Print" and "Visualize".

![image](https://cloud.githubusercontent.com/assets/16255219/20278979/6cd80dc0-aaaf-11e6-8c07-d8a0e6b207d0.png)

Thanks

Melissa

**Comment by berkantesk** [comment]
Fixed
