### ISSUE TITLE
Error after latest Lang Merge

### ISSUE THREAD

**Issue by koc-university** [kocun/heida#124]
After latest merge and deployment there is a javascript in console .

angular.js:38Uncaught Error: [$injector:unpr] http://errors.angularjs.org/1.5.8/$injector/unpr?p0=%24translateStaticFilesLoaderProvider%20%3C-%20%24translateStaticFilesLoader
    at 

http://heida.test.ku.edu.tr/

**Comment by berkantesk** [comment]
fixed
