### ISSUE TITLE
Frontend Editor Add Indicator needs fixing

### ISSUE THREAD

**Issue by melissaabache** [kocun/heida#167]
@berkantesk @ogzhnozlci @adilatilgan 

On Editor Menu - Indicators add GROUP list before SUB-GROUP list
After clicking on "Add new indicator" all Editors should have authorization to click on "Add" and the indicator should be saved 
On "Add new indicator" add GROUP list before SUB-GROUP list

On "Add Data" Menu when filtering by group and subgroup it should show any new indicators created by editors with a new code at the end.

![image](https://cloud.githubusercontent.com/assets/16255219/22499039/1c0ac2b8-e865-11e6-92b6-dc69489e8467.png)

**Comment by berkantesk** [comment]
fixed
