### ISSUE TITLE
Frontend Editor Menu - Indicators - Missing/Not showing indicators

### ISSUE THREAD

**Issue by melissaabache** [kocun/heida#169]
@berkantesk @ogzhnozlci thanks for your work. Still need to fix the following on "Editor" Menu - "İndicators"

Issue 1 - when I filter by group (example "Administration") and subgroup (example "Administration") it is not showing the indicators (see screenshot). Please check that all 489 indicators have been uploaded with their group and subgroup 

Issue 2 - when I click on "Add indicator" it should show in the columns Name then **GROUP** (missing now) then SUBGROUP then all the other boxes (value type, goal 1, goal 2....)

![image](https://cloud.githubusercontent.com/assets/16255219/22691472/532ab7fc-ed43-11e6-9c8b-669eee7b9579.png)

![image](https://cloud.githubusercontent.com/assets/16255219/22691622/f4c027a0-ed43-11e6-8fb1-14f47529c157.png)

**Comment by berkantesk** [comment]
Issue 2 fixed.

@adilatilgan please check on DB indicator groups.
