### ISSUE TITLE
FE: Bug on angular

### ISSUE THREAD

**Issue by adilatilgan** [kocun/heida#176]
bower installs version angular 1.6.3 which is buggy for older sites. 
down grade all angular platform to 1.6.2 . 

Get a clean copy and do bower install to find this bug.

**Comment by berkantesk** [comment]
fixed

**Comment by adilatilgan** [comment]
Did not  work, https://heida-tool.ku.edu.tr

**Comment by berkantesk** [comment]
I forgot changed api urls this page. 

https://github.com/kocun/heida/blob/master/assets/scripts/controllers/main.js

**Comment by berkantesk** [comment]
Fixed 3 April.
