### ISSUE TITLE
Kurulum Sonrası Beyaz Sayfa

### ISSUE THREAD

**Issue by digifelis** [kocun/heida#181]
ubuntu 14.04 sürümünde kurulum adımları tam olarak uygulandıktan ve "sails lift" komutu sorunsuz olarak çalıştıktan sonra web tarayıcı ile heida yazılımına bağlandığımızda ekran boş gelmektedir.
![adsiz](https://user-images.githubusercontent.com/5615913/30198180-0104ef54-9475-11e7-9d2a-3fdcb5c0fe47.png)

**Comment by canturkm** [comment]
Bizim durumumuzda assets klasörüne geçiş yapıp (cd assets) "bower install" komutunu çalıştırınca düzeldi. Tabi bunun için sisteminizde bower yüklü değilse yüklemeniz lazım.
