### ISSUE TITLE
Backend : Check default admin user

### ISSUE THREAD

**Issue by adilatilgan** [kocun/heida#27]
Create a local admin user with default password, when the app is installed first that user might able to login and force change password change.

**Comment by zafertaskent** [comment]
@adilatilgan How about this, in the local.js file we configure email address of the admin and then when the user first login we persist him/her as admin? Then we do not need to deal with password issue. 
We can write in the installation note about this.

**Comment by adilatilgan** [comment]
Sounds good, make it admins and array, better to configure more than one users as admin.

**Comment by zafertaskent** [comment]
I am stuck on this @adilatilgan . When the user first logins, user is persisted on db but application waits in endless loop. Server does not return any response. Can you check this for me @adilatilgan

**Comment by adilatilgan** [comment]
It is on line 177 of passport.js . You have if without brackets and two lines after. use bracket there. 
And also format the code. It is very hard to read.

**Comment by zafertaskent** [comment]
It worked, thanks you save my day. I will format the code.
