### ISSUE TITLE
Backend - Create success indicators service

### ISSUE THREAD

**Issue by berkantesk** [kocun/heida#31]
Create service for success indicators or create success state on api/data service.

**Comment by zafertaskent** [comment]
Bu durumu anlayamadım. Akışa hakim değilim. Biraz anlatırmısın @berkantesk

**Comment by adilatilgan** [comment]
Please use English here, this is an open source project for whole of the world. Edit and translate your comments please.

**Comment by adilatilgan** [comment]
Data backend has only successful indicator, closing.
