### ISSUE TITLE
Backend - Get Google Plus user picture

### ISSUE THREAD

**Issue by berkantesk** [kocun/heida#38]
/profile sayfasında kullanıcının avatarının getirilmesi. Oauth da değişken var fakat undefined geliyor. Sanırım backendcinin bakması gerekiyor.

**Comment by zafertaskent** [comment]
@berkantesk @ogzhnozlci This is done . Now user object has avatar field holding the image for user. 
Please note: It does not work with already registered users. Remove them and login again.
