### ISSUE TITLE
BackEnd - api/data/indicatorId service needs some revisions

### ISSUE THREAD

**Issue by ogzhnozlci** [kocun/heida#52]
"Create data" page is using ('/api/data/'+$scope.ind.id) service. But, according to "HEIDA database final EN.xlsx", that service need some revisions.

This revisions are;
* "criterias of selected indicator" must be in this service. 
	Example response; 
	[
		{
			criterias : {
			'//question id' : '// answer id',
			'// question id': [//answer id, //answer id]  // Array for multiple selected ansers
			}
		}
	]
	
* "goals of selected indicator" must be in this service.
	Example response; 
	[
		{
			goals: "// goal id"
		}
	]
	
* "group of selected indicator" must be in this service.
	Example response; 
	[
		{
			group: "// group id"
		}
	]
	
* "subgroup of selected indicator" must be in this service.
	Example response; 
	[
		{
			subgroup: "// subgroup id"
		}
	]

* "indicators" must be array. because, User can select multiple indicator for a data.
	Example response; 
	[
		{
			indicators: ["// indicator id", "//indicator id"]
		}
	]
	
* "public" is a boolean now. but there is 3 selection ("Public","Staff only","Not sure") for "public". Maybe "public" has a string type.
	Example response; 
	[
		{
			public: "Staff"
		}
	]
	
* "subUnit of selected indicator" must be in this service.
	Example response; 
	[
		{
			subunit: "// subunit id"
		}
	]
	
* "periodType of selected indicator" must be in this service.
	Example response; 
	[
		{
			periodType: "academic" or "calendar"
		}
	]
	
* "years of selected indicator" must be obj in this service. Because use can select multiple year and also user can enter value for each selected year.
	Example response; 
	[
		{
			years: criterias : {
			'//selected year' : '// value of year',
			'//selected year': '// value of year',
			'//selected year': '// value of year'
			}
		}
	]
	

[HEIDA database final EN.zip](https://github.com/kocun/heida/files/454038/HEIDA.database.final.EN.zip)

**Comment by zafertaskent** [comment]
wont fix
