### ISSUE TITLE
Frontend - create data section - hide the initial list of indicators

### ISSUE THREAD

**Issue by melissaabache** [kocun/heida#67]
http://heida.test.ku.edu.tr/#/dashboard/data

Hide list of indicators - they should only appear after you select Group and Sub Group and click on filter
![image](https://cloud.githubusercontent.com/assets/16255219/18664156/24529bde-7f2a-11e6-901c-009af82f81e2.png)

**Comment by adilatilgan** [comment]
Test comment for email update

**Comment by adilatilgan** [comment]
@melissaabache you hear me now

**Comment by ogzhnozlci** [comment]
Done
