### ISSUE TITLE
type of sub-unit open text box (Other selection)

### ISSUE THREAD

**Issue by melissaabache** [kocun/heida#68]
After selecting "Type of Unit" the next step should be an open text box that says on top "Write the name of your unit"

![image](https://cloud.githubusercontent.com/assets/16255219/18664361/f9b6172e-7f2a-11e6-8745-4dabea7ddf3a.png)

**Comment by ogzhnozlci** [comment]
If user selects "other" ( at the end of the select list), a text box appear for new unit. 

But I don't have any idea about that "backend service has a potential to save a custom unit and give it via service to FrontEnd"

@zafertaskent will answer, i think.

**Comment by melissaabache** [comment]
@ogzhnozlci @adilatilgan @berkantesk I have updated the Department and Sub-Department List but please change the name to Unit and Sub-Unit respectively. I also tried to delete the previous Department items but could only delete the name so they show as a blank space on the drop down menu. The Unit list should only show: Academic Unit, Non-Academic Unit, Research Unit and Other (in that order) Thanks!

**Comment by zafertaskent** [comment]
I have added departmentDesc field to data endpoint

**Comment by ogzhnozlci** [comment]
Done
