### ISSUE TITLE
BackEnd - Reports section 

### ISSUE THREAD

**Issue by melissaabache** [kocun/heida#76]
Report section should be like this

![image](https://cloud.githubusercontent.com/assets/16255219/18665210/cd5bf55a-7f2e-11e6-968e-43927af5d479.png)

**Comment by ogzhnozlci** [comment]
There is no "Indicator Code","Status" columns in data. Also we dont have any "delete" operations on this Project. Backend must be work on this bug. Then we will develop for this design

**Comment by adilatilgan** [comment]
@zafertaskent instead of status put a fields that show  indicator has a data or not

**Comment by melissaabache** [comment]
@zafertaskent we have indicator code area on data service. And we work delete functionality.

**Comment by zafertaskent** [comment]
All end points have built in CRUD operations. Delete is explained here. 
http://sailsjs.org/documentation/reference/blueprint-api/remove-from

**Comment by zafertaskent** [comment]
@adilatilgan I am clear with "show indicator has a data or not"

**Comment by adilatilgan** [comment]
@zafertaskent I am talking the same http://heida.test.ku.edu.tr/#/dashboard/groups shows us number of sub-groups.

**Comment by zafertaskent** [comment]
That is client side 
https://github.com/kocun/heida/blob/master/assets/views/pages/groups.html
line 26

**Comment by adilatilgan** [comment]
Work with indicator code while I am investigating on this.

**Comment by zafertaskent** [comment]
Fixed with https://github.com/kocun/heida/pull/78

**Comment by berkantesk** [comment]
@zafertaskent i can't see indicator code, group and status on data service. Do i need to do anything extra?

@adilatilgan @ogzhnozlci

**Comment by zafertaskent** [comment]
it should be there if you create a new indicator. all the ones have no code

**Comment by zafertaskent** [comment]
code is in indicator service not in data. Data has indicator. If you create a new indicator with code, you should see it in data service
