### ISSUE TITLE
Front end - Create data section - Indicators not showing again

### ISSUE THREAD

**Issue by melissaabache** [kocun/heida#80]
@adilatilgan After selecting goal, group and sub-group and clicking on filter it is not showing any indicators. Please fix this asap

**Comment by melissaabache** [comment]
@adilatilgan specifically when I tried Group Research and Sub-Group Researcher Activity

**Comment by ogzhnozlci** [comment]
@melissaabache i just tried some filter and i saw that filter is working. Could you try filter via "goal1 & Student & Student abroad" datas?

*Filter only work when selected goal is highly.

**Comment by adilatilgan** [comment]
Filter here works only for "highly relevant", I have asked @ogzhnozlci to lower to it moderate or higher.

**Comment by berkantesk** [comment]
@melissaabache said that way we talked about yesterday.

**Comment by melissaabache** [comment]
@berkantesk OK let's make filter as Adil said and show for each goal those indicators that are "Moderate" and "Highly" so it shows more indicators for each goal thanks

**Comment by berkantesk** [comment]
fixed.
