### ISSUE TITLE
Frontend - create data section Criteria questions are not showing please fix

### ISSUE THREAD

**Issue by melissaabache** [kocun/heida#81]
@ogzhnozlci @adilatilgan in Create Data the Criteria questions are not showing please fix asap tonight - urgent! Thanks

**Comment by ogzhnozlci** [comment]
@adilatilgan i checked for this bug and also i saw that " criterias service don't have questions datas anymore". Because of this situation, answers dont show.

**Comment by adilatilgan** [comment]
that is fixed now
