### ISSUE TITLE
Frontend - Reports section - change order of columns at the top and filter 

### ISSUE THREAD

**Issue by melissaabache** [kocun/heida#82]
@ogzhnozlci @berkantesk on Reports section top columns order should be:
Unit - Sub-Unit-Name of Unit-Indicator then blue Filter button then Red Clear button

Right now it is showing a list of indicators that has no relation to anything? The indicators that show after selecting Unit - Sub-Unit - Name of Unit are those that have been completed by that Unit-Sub-Unit only

thanks

**Comment by melissaabache** [comment]
@ogzhnozlci @berkantesk this issue hasn't been solved (see above). Also saw latest changes and it is looking better but additional things to fix are:
1) Sub-group on the table is showing codes that shouldn't be there - Sub-Group column should show sub-group category
2) Status should be "Completed" (green color) and "Incomplete" (red color)
**3) Actions - Edit when you click it takes you to the start of Create Data process. It should take you to the individual indicator to edit it**

From this issue please ensure these things are done:
4) Reports section top columns order should be:
Unit - Sub-Unit-Name of Unit-Indicator then blue Filter button then Red Clear button
Please give me a call if it is easier to explain over the phone

![image](https://cloud.githubusercontent.com/assets/16255219/18872842/1ba787a6-84c5-11e6-9bac-e048b2661784.png)

**Comment by melissaabache** [comment]
@ogzhnozlci @berkantesk also when you click on Visualize (Graph/Table) it is not showing any graphs. I added data for indicator 05-011 "Out of all the programme elements/modules offered by the unit in a given year, what is the proportion of those focused on international/intercultural skills?" and it is not showing a graph

**Comment by berkantesk** [comment]
@melissaabache hi, i started edit action. But our structure not supported this. Edit Data anchor, open edit data row on create page. So this page does not bring indicator filter from filling. It does not automatically reached. If you confirm; we want to make a new page edit data areas like indicator edit page.

P.S: I explained to @adilatilgan . You can learn details from him.

Thanks

**Comment by melissaabache** [comment]
@berkantesk OK I talked to Adil so please do new Edit Data page

**Comment by berkantesk** [comment]
fixed
