### ISSUE TITLE
Frontend - Edit Data - Sub-Unit and Name of Unit should be fixed

### ISSUE THREAD

**Issue by melissaabache** [kocun/heida#86]
@ogzhnozlci @berkantesk @adilatilgan  When editing indicators the "Sub-Unit" and "Name of Unit" should be fixed/remembered. Right now it goes to blank and user has to choose again.

**Comment by ogzhnozlci** [comment]
@adilatilgan Name Of unit added on edit data page.  But can't access to subunit id on data/data.id endpoint. There is Main department info not sub department info in data/data.id  -> department_sub

**Comment by adilatilgan** [comment]
@ogzhnozlci 

Which data is missing here?
http://heida.test.ku.edu.tr/api/data/58007aa69e398d6a45f77ac7

![screen shot 2016-10-14 at 9 29 58 am](https://cloud.githubusercontent.com/assets/890600/19377709/f634c6da-91f0-11e6-8b60-64c543d8ffde.png)

**Comment by berkantesk** [comment]
fixed
