### ISSUE TITLE
Frontend - Search - show indicator code, indicator name, Group and Sub-Group on results

### ISSUE THREAD

**Issue by melissaabache** [kocun/heida#88]
@ogzhnozlci @berkantesk @adilatilgan On search function: the results table should show in this order:
Indicator Code - Indicator Name - Group - Sub-Group 
Thanks

**Comment by melissaabache** [comment]
![image](https://cloud.githubusercontent.com/assets/16255219/18904649/f104ab70-8567-11e6-9b1c-466006c84443.png)

**Comment by melissaabache** [comment]
On search results when clicking on an indicator it should take to the indicator Report.

If there is no data for that indicator then it should show this message "There is no data for this indicator"

**Comment by berkantesk** [comment]
Indicators has not group info. When we first set up such architecture. So we can show only subgroup.

**Comment by berkantesk** [comment]
Added indicator code and sub-group
