### ISSUE TITLE
Frontend - Security Change in Menu

### ISSUE THREAD

**Issue by adilatilgan** [kocun/heida#90]
Admin Menu (only admin access Role 4)

- Change name of the menu to Admin Menu

- Only admins can access to Admin menu

- Remove all sub-menu's from Admin menu except for users

Editor Menu (admin and editor access Role 4 and 3)

- Create a new Menu , Name: Editor Menu

- All current sub-menus should be moved here(except for users) here

**Comment by berkantesk** [comment]
fixed
