### ISSUE TITLE
Backend: Data response Populate Sub Department and department name

### ISSUE THREAD

**Issue by adilatilgan** [kocun/heida#91]

**Comment by zafertaskent** [comment]
This is really hardwork in async platform. @adilatilgan I explained you in phone.

**Comment by zafertaskent** [comment]
It is better calling subdepartment endpoint for each record 

http://heida.test.ku.edu.tr/api/subdepartment?department=5756a4116ecb6afd7fd51978

**Comment by adilatilgan** [comment]
I have checked again @zafertaskent data entries have their own sub-department and department name as text. 
So Data model should have subgroup as well as free text area. It seems like departmentDesc is the free text area but you should add sub-departments to model.

**Comment by zafertaskent** [comment]
OK it is clear now

**Comment by adilatilgan** [comment]
Done
