### ISSUE TITLE
Frontend- Report pages must show data

### ISSUE THREAD

**Issue by adilatilgan** [kocun/heida#92]
Type of unit
Type of sub -unit missing Fixed by  [https://github.com/kocun/heida/issues/91](url)
Name of unit - missing Fixed by  [https://github.com/kocun/heida/issues/91](url)
Time Period
Years / Values
Criteria 1 - Yes
Criteria 2 - Usually
..
..

**Comment by berkantesk** [comment]
We will wait BE development.

**Comment by adilatilgan** [comment]
BE is ready

**Comment by ogzhnozlci** [comment]
Resolved.

**Comment by berkantesk** [comment]
fixed
