### ISSUE TITLE
SubUnit and UnitName show on edit data

### ISSUE THREAD

**Issue by ogzhnozlci** [kocun/heida#95]
I made some revisions about show SubUnit and UnitName on editing data. 

I use api/data/dataId endpoint. And also departmentDesc for unitname. But I didn't see any subdepartment id in that endpoint. 

For now, I post new/edited unitName value and subUnit id via departmentDesc and subdepartment keys to api/data/dataId endpoint.

I think, need a control for api/data/dataId endpoint .

**Comment by adilatilgan** [comment]
Done,

http://heida.test.ku.edu.tr/api/data/57fa0901ffe0238f60d43a30
